# 1.라이브러리 불러오기

In [1]:
import pandas as pd
import numpy as np

In [36]:
from sklearn.preprocessing import LabelEncoder

### 2.데이터 불러오기

In [5]:
featureData = pd.read_csv("../../1학기/dataset/kopo_decision_tree_all_new.csv")
featureData.head()

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT
0,A01,PG01,P01,ITEM001,201538,2015,38,1,N,4,N,0.0
1,A01,PG01,P01,ITEM001,201548,2015,48,1,Y,0,N,0.0
2,A01,PG01,P01,ITEM001,201549,2015,49,2,Y,0,N,0.0
3,A01,PG01,P01,ITEM002,201526,2015,26,1,Y,1,N,0.0
4,A01,PG01,P01,ITEM002,201532,2015,32,1,N,4,N,0.0

In [7]:
featureData.shape

(32415, 12)

### 3.머신러닝 적용성 체크

In [10]:
### 머신러닝을 50건 이상인 아이템에 대해서만 돌리겠다.

In [13]:
# pk를 정확히 확인해야한다.
groupKey = ["REGIONID", "ITEM"]

In [19]:
groupData = featureData.groupby(by = groupKey)[["YEARWEEK"]].agg("count").reset_index()
groupData.rename(columns={"YEARWEEK": "YEARWEEK_CNT"}, inplace=True)
groupData

    REGIONID     ITEM  YEARWEEK_CNT
0        A01  ITEM001             3
1        A01  ITEM002             2
2        A01  ITEM003             1
3        A01  ITEM004             7
4        A01  ITEM005             8
..       ...      ...           ...
486      A01  ITEM487            31
487      A01  ITEM488            29
488      A01  ITEM489            94
489      A01  ITEM490            92
490      A01  ITEM491             5

[491 rows x 3 columns]

In [20]:
### 데이터 병합 (기존데이터 + 카운트 데이터)

In [22]:
mergedData = pd.merge(left = featureData, right= groupData, on=groupKey)
mergedData

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT,YEARWEEK_CNT
0,A01,PG01,P01,ITEM001,201538,2015,38,1,N,4,N,0.0,3
1,A01,PG01,P01,ITEM001,201548,2015,48,1,Y,0,N,0.0,3
2,A01,PG01,P01,ITEM001,201549,2015,49,2,Y,0,N,0.0,3
3,A01,PG01,P01,ITEM002,201526,2015,26,1,Y,1,N,0.0,2
4,A01,PG01,P01,ITEM002,201532,2015,32,1,N,4,N,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32410,A01,PG05,P16,ITEM491,201503,2015,3,1,N,4,N,0.0,5
32411,A01,PG05,P16,ITEM491,201504,2015,4,1,Y,2,N,0.0,5
32412,A01,PG05,P16,ITEM491,201505,2015,5,2,N,4,N,0.0,5
32413,A01,PG05,P16,ITEM491,201506,2015,6,1,N,4,N,0.0,5
32414,A01,PG05,P16,ITEM491,201508,2015,8,1,Y,1,N,0.0,5

In [23]:
mlActive = 50

In [25]:
mlTargetData = mergedData.loc[mergedData.YEARWEEK_CNT > mlActive]

In [30]:
mergedData.drop_duplicates(groupKey).shape

(491, 13)

In [29]:
mlTargetData.drop_duplicates(groupKey).shape

(258, 13)

### 4.머신러닝 적용

In [33]:
mlTargetData = mlTargetData.reset_index(drop=True)
mlTargetData

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT,YEARWEEK_CNT
0,A01,PG01,P01,ITEM007,201501,2015,1,64,Y,1,Y,0.230354,89
1,A01,PG01,P01,ITEM007,201502,2015,2,53,N,4,Y,0.231741,89
2,A01,PG01,P01,ITEM007,201503,2015,3,67,N,4,Y,0.231741,89
3,A01,PG01,P01,ITEM007,201504,2015,4,74,Y,2,Y,0.231741,89
4,A01,PG01,P01,ITEM007,201505,2015,5,35,N,4,Y,0.231741,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26650,A01,PG05,P16,ITEM490,201636,2016,36,11,Y,1,Y,0.211294,92
26651,A01,PG05,P16,ITEM490,201637,2016,37,3,N,4,Y,0.211294,92
26652,A01,PG05,P16,ITEM490,201638,2016,38,7,N,4,N,0.000000,92
26653,A01,PG05,P16,ITEM490,201639,2016,39,3,N,4,N,0.000000,92
26654,A01,PG05,P16,ITEM490,201640,2016,40,1,N,4,N,0.000000,92

### 4-1 특성선정

In [38]:
ynle = LabelEncoder()

In [42]:
mlTargetData["HOLIDAY_YN"] = ynle.fit_transform(mlTargetData.HOLIDAY)

In [44]:
yn2le = LabelEncoder()

In [45]:
mlTargetData["PROMOTION_YN"] = yn2le.fit_transform(mlTargetData.PROMOTION)

In [46]:
mlTargetData

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT,YEARWEEK_CNT,HOLIDAY_YN,PROMOTION_YN
0,A01,PG01,P01,ITEM007,201501,2015,1,64,Y,1,Y,0.230354,89,1,1
1,A01,PG01,P01,ITEM007,201502,2015,2,53,N,4,Y,0.231741,89,0,1
2,A01,PG01,P01,ITEM007,201503,2015,3,67,N,4,Y,0.231741,89,0,1
3,A01,PG01,P01,ITEM007,201504,2015,4,74,Y,2,Y,0.231741,89,1,1
4,A01,PG01,P01,ITEM007,201505,2015,5,35,N,4,Y,0.231741,89,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26650,A01,PG05,P16,ITEM490,201636,2016,36,11,Y,1,Y,0.211294,92,1,1
26651,A01,PG05,P16,ITEM490,201637,2016,37,3,N,4,Y,0.211294,92,0,1
26652,A01,PG05,P16,ITEM490,201638,2016,38,7,N,4,N,0.000000,92,0,0
26653,A01,PG05,P16,ITEM490,201639,2016,39,3,N,4,N,0.000000,92,0,0
26654,A01,PG05,P16,ITEM490,201640,2016,40,1,N,4,N,0.000000,92,0,0

In [49]:
# 주차에 영향을 받지 않거나, 할인에 영향을 받지 않을 수도 있다.
# 장난감은 어린이날 같은 때에 잘 팔리고, 가전은 할인이 높으면 잘 팔린다.
mlTargetData.corr()

,YEARWEEK,YEAR,WEEK,QTY,HCLUS,PRO_PERCENT,YEARWEEK_CNT,HOLIDAY_YN,PROMOTION_YN
YEARWEEK,1.000000,0.982282,-0.045837,-0.023741,0.029537,0.210547,-0.081379,-0.014555,0.117624
YEAR,0.982282,1.000000,-0.232237,-0.043548,0.087291,0.171298,-0.075691,-0.061334,0.103820
WEEK,-0.045837,-0.232237,1.000000,0.108907,-0.311993,0.179678,-0.018902,0.251388,0.057078
QTY,-0.023741,-0.043548,0.108907,1.000000,-0.197787,0.256510,0.094327,0.169762,0.114726
HCLUS,0.029537,0.087291,-0.311993,-0.197787,1.000000,-0.289875,0.005298,-0.976463,-0.120235
PRO_PERCENT,0.210547,0.171298,0.179678,0.256510,-0.289875,1.000000,0.092821,0.250183,0.797245
YEARWEEK_CNT,-0.081379,-0.075691,-0.018902,0.094327,0.005298,0.092821,1.000000,-0.004097,0.171862
HOLIDAY_YN,-0.014555,-0.061334,0.251388,0.169762,-0.976463,0.250183,-0.004097,1.000000,0.112016
PROMOTION_YN,0.117624,0.103820,0.057078,0.114726,-0.120235,0.797245,0.171862,0.112016,1.000000

### 4-2.특성선정 groupby

In [117]:
def mlGroup(eachData):
    print(eachGroup.loc[:,groupKey].head(1))
    # groupData = mlTargetData.groupby(by=groupKey)

    # eachGroup = groupData.get_group(list(groupData.groups)[2])
    eachGroup

    corrDf = eachGroup.corr()

    # for문으로 start와 end를 돌려서 feature를 끄집어내서 만든다.
    stdCorr = 0.2

    label = ["QTY"]

    features = list(corrDf.loc[(corrDf.QTY > stdCorr) & (corrDf.QTY != 1)].index)
    features

    ### 4-3.데이터 분리

    from sklearn.model_selection import train_test_split

    train_feat,\
    test_feat,\
    train_label,\
    test_label= train_test_split(eachGroup.loc[:,features],
                                 eachGroup.loc[:,label],
                                 test_size=0.2)

    print(train_feat.shape)
    print(train_label.shape)
    print(test_feat.shape)
    print(test_label.shape)

    ### 4-4.데이터 머신러닝 적용

    from sklearn.tree import DecisionTreeRegressor

    modelDt = DecisionTreeRegressor(random_state=10)

    modelDtFit = modelDt.fit(X = train_feat, y = train_label)

    ### 4-5.

    pradictValue = modelDtFit.predict(test_feat)

    testIndex = test_feat.index

    testDataAll = eachGroup.loc[testIndex]

    testDataAll["PRADICT_DT"] = pradictValue

    return testDataAll

In [116]:
groupData = mlTargetData.groupby(by=groupKey).apply(mlGroup)
groupData

    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)
    REGIONID     ITEM
182      A01  ITEM009
(71, 3)
(71, 1)
(18, 3)
(18, 1)

                     REGIONID PRODUCTGROUP PRODUCT     ITEM  YEARWEEK  YEAR  \
REGIONID ITEM
A01      ITEM007 197      A01         PG01     P01  ITEM009    201516  2015
                 218      A01         PG01     P01  ITEM009    201537  2015
                 191      A01         PG01     P01  ITEM009    201510  2015
                 194      A01         PG01     P01  ITEM009    201513  2015
                 192      A01         PG01     P01  ITEM009    201511  2015
...                       ...          ...     ...      ...       ...   ...
         ITEM490 221      A01         PG01     P01  ITEM009    201540  2015
                 268      A01         PG01     P01  ITEM009    201634  2016
                 196      A01         PG01     P01  ITEM009    201515  2015
                 203      A01         PG01     P01  ITEM009    201522  2015
                 237      A01         PG01     P01  ITEM009    201603  2016

                      WEEK  QTY HOLIDAY  HCLUS PROMOTION  PRO_PERCENT  \
REGIONID ITEM
A01      ITEM007 197    16   13       N      4         N     0.000000
                 218    37   27       Y      1         Y     0.154083
                 191    10   29       N      4         Y     0.154083
                 194    13   18       N      4         Y     0.154083
                 192    11   27       N      4         Y     0.154083
...                    ...  ...     ...    ...       ...          ...
         ITEM490 221    40   24       N      4         Y     0.154083
                 268    34    1       Y      1         N     0.000000
                 196    15   20       N      4         Y     0.154083
                 203    22   26       Y      1         Y     0.154083
                 237     3   34       Y      2         Y     0.308012

                      YEARWEEK_CNT  HOLIDAY_YN  PROMOTION_YN  PRADICT_DT
REGIONID ITEM
A01      ITEM007 197            89           0             0    8.166667
                 218            89           1             1   15.200000
                 191            89           0             1   13.266667
                 194            89           0             1   13.266667
                 192            89           0             1   13.266667
...                            ...         ...           ...         ...
         ITEM490 221            89           0             1   15.647059
                 268            89           1             0    4.000000
                 196            89           0             1   15.647059
                 203            89           1             1   15.000000
                 237            89           1             1   49.000000

[4644 rows x 16 columns]

In [118]:
import pickle

In [122]:
# 딕셔너리 (key,value) 키로 그룹키를 던질거고
# value feature가 뭘로 구성되어 있고 훈련 결과는 무엇이다.
modelDict = {}

In [123]:
# 모델 저장시 그룹키 요청시 feature및 학습결과 나오도록 저장
modelDict[eachGroup.REGIONID.values[0], eachGroup.ITEM.values[0]] = [features, modelDtfit]
# modelDtfit 이부분은 함수에 들어가면서 없어졌기에 찍을 수 없다.

NameError: name 'modelDtfit' is not defined