In [19]:
import pymysql
from sqlalchemy import create_engine
from sqlalchemy import types
import pandas as pd
import os
import cv2

In [25]:
df1 = pd.read_csv("./22_1.csv")
df1

,상품명,금융회사,상품유형,최초판매일,판매여부,중도해지,'22년 1분기,Unnamed: 7,Unnamed: 8,'21년,Unnamed: 10,Unnamed: 11,장기 수익률(연평균),Unnamed: 13,Unnamed: 14,Unnamed: 15,장기 수수료율(연평균),Unnamed: 17,Unnamed: 18,Unnamed: 19
0,상품명,금융회사,상품유형,최초판매일,판매여부,중도해지,납입원금,적립금,수익률,납입원금,적립금,수익률,3년,5년,7년,10년,3년,5년,7년,10년
1,연금저축손해보험 삼성화재 연금보험 아름다운생활(1106.8)/(1111.9),삼성화재해상보험,금리연동형,2011/06/01,중단,불가능,"1,972,641","2,045,385",1.50,"2,016,306","2,082,999",1.47,1.32,1.11,0.87,-0.58,1.02,1.2,1.47,3.09
2,연금저축손해보험 삼성화재 연금보험 아름다운생활(1004.6),삼성화재해상보험,금리연동형,2010/04/01,중단,불가능,"1,634,595","1,759,756",1.50,"1,686,945","1,808,367",1.49,1.53,1.37,1.23,0.92,0.66,0.88,1.11,1.82
3,연금저축신탁 안정형제1호,신한은행,안정형,2005/03/23,중단,가능,"1,332,184","1,610,935",-1.02,"1,362,391","1,650,997",-0.05,0.64,0.94,1.34,1.78,0.79,0.79,0.79,0.81
4,연금저축손해보험 삼성화재 연금보험 아름다운생활(1204.10),삼성화재해상보험,금리연동형,2012/04/01,중단,불가능,"1,469,074","1,484,076",1.54,"1,447,313","1,456,663",1.50,1.26,0.89,0.47,NaN,1.04,1.35,1.79,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3246,미래에셋클린테크증권자투자신탁(주식)종류C-P2,미래에셋자산운용,재간접,2021/03/04,판매,가능,110,96,-19.95,27,26,-8.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3247,KB연금이머징인덱스증권자투자신탁(주식-파생형)C-E,케이비자산운용,파생상품,2017/08/23,판매,가능,105,91,-13.61,102,95,-4.78,4.78,NaN,NaN,NaN,0.72,NaN,NaN,NaN
3248,한국투자SSGA글로벌저변동성증권자투자신탁UH(주식)(S-P),한국투자신탁운용,주식형,2018/05/14,판매,가능,125,89,8.82,117,81,13.10,-9.46,NaN,NaN,NaN,0.70,NaN,NaN,NaN
3249,NH-Amundi아세안플러스증권투자신탁 1[주식]C-P1(연금저축),엔에이치아문디자산운용,주식형,2016/09/30,판매,가능,110,85,11.52,110,81,12.84,3.19,0.57,NaN,NaN,1.20,1.27,NaN,NaN
3250,키움코스닥SmartInvestor목표전환증권투자신탁 1[혼합-재간접형]ClassC-Pe,키움투자자산운용,재간접,2018/01/31,판매,가능,104,43,-3.56,104,49,-1.08,2.35,NaN,NaN,NaN,0.41,NaN,NaN,NaN

In [26]:
inId = "root"
inPw = "0000"
inIp = "127.0.0.1"
inPort = "3306"
inDbName = "web"

In [28]:
engine = create_engine("mysql+pymysql://{}:{}@{}:{}/{}".format(inId,inPw,inIp,inPort,inDbName))

tableName = "TEST_3"
tableName = tableName.upper()
#### 문자컬럼에 대해서 varchar (100) 적용 _ 사용시 속도 SpeedUp 50배 
objectColumns = list(df1.columns[df1.dtypes == 'object'])
typeDict={}
maxLen = 100

for i in range(0, len(objectColumns)):
    # sawonData[i].str.len().max() 최대치 사용할 경우
    typeDict[ objectColumns[i] ] = types.VARCHAR(100)
#### 문자컬럼에 대해서 varchar (100) 적용 _ 사용시 속도 SpeedUp 50배 

df1.to_sql(name=tableName, if_exists="replace", con=engine,dtype=typeDict, index=False)

C:\Users\caose\anaconda3\lib\site-packages\pandas\io\sql.py:1666: UserWarning: The provided table name 'TEST_3' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  warnings.warn(msg, UserWarning)

3251